jQuery("#wowslider-container8").wowSlider({
    effect: "fade",
    prev: "",
    next: "",
    duration: 10 * 100,
    delay: 30 * 100,
    width: 571,
    height: 800,
    autoPlay: true,
    autoPlayVideo: false,
    playPause: true,
    stopOnHover: false,
    loop: false,
    bullets: 0,
    caption: false,
    captionEffect: "move",
    controls: true,
    controlsThumb: false,
    responsive: 1,
    fullScreen: false,
    gestures: 2,
    onBeforeStep: 0,
    images: 0
});